version: '3.8'
services:
  oracle:
    image: gvenzl/oracle-xe:21
    container_name: oracle-xe
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=s381731
      - APP_USER_PASSWORD=s381731
    ports:
      - "38177:1521"
    volumes:
      - oracle_data:/opt/oracle/oradata
      - ./sql/init.sql:/container-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  oracle_data: