plugins {
    id 'java'
    id 'war'
    id 'org.gretty' version '4.1.0'
}

version = '1.0.0'
sourceCompatibility = '15'
targetCompatibility = '15'

repositories {
    mavenCentral()
}

dependencies {
    implementation 'jakarta.platform:jakarta.jakartaee-api:9.1.0'
    implementation 'org.glassfish:jakarta.faces:3.0.3'
    implementation 'org.postgresql:postgresql:42.6.0'
    implementation 'com.fasterxml.jackson.core:jackson-core:2.15.2'

    implementation 'org.primefaces:primefaces:13.0.0:jakarta'

    providedCompile 'jakarta.servlet:jakarta.servlet-api:5.0.0'

    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.2'
    testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.9.2'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

war {
    archiveFileName = 'web.war'
}

gretty {
    httpPort = 8080
    contextPath = '/'
    servletContainer = 'tomcat10'
    jvmArgs = ['-Xdebug', '-Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=5005']

    // Для избежания конфликтов портов
    inplaceMode = 'hard'
}