version: '3.8'
services:
  postgres:
    image: postgres:16.4
    container_name: postgres-db
    environment:
      - POSTGRES_DB=s381731
      - POSTGRES_USER=s381731
      - POSTGRES_PASSWORD=s381731
    ports:
      - "38177:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

volumes:
  postgres_data: