CREATE USER s381731 IDENTIFIED BY s381731;
GRANT CONNECT, RESOURCE TO s381731;
GRANT UNLIMITED TABLESPACE TO s381731;
GRANT CREATE TABLE TO s381731;
GRANT CREATE SEQUENCE TO s381731;


CREATE TABLE point_results (
    id NUMBER PRIMARY KEY,
    x NUMBER NOT NULL,
    y NUMBER NOT NULL,
    r NUMBER NOT NULL,
    result NUMBER(1) NOT NULL,
    timestamp TIMESTAMP NOT NULL,
    execution_time NUMBER NOT NULL
);

CREATE SEQUENCE point_seq
    START WITH 1
    INCREMENT BY 1
    NOMAXVALUE
    NOCACHE
    NOCYCLE;